### ISSUE TITLE
About the paper and video

### ISSUE THREAD

**Issue by Bailey-24** [arthurfenderbucker/LaTTe-Language-Trajectory-TransformEr#2]
In this video, https://www.youtube.com/watch?v=Kutc_peSrpw ,  the human say "reduce a lot the speed when close to me" after the origin trajectory, but How do we know the origin trajectory is safety or not?

**Comment by arthurfenderbucker** [comment]
The system should be useful to correct recurrent mistakes of the robot or change it online (if the human has access to the original trajectory planned). The idea is that, in this case, if the robot was moving too fast for the user, the human could use language to express what he wants to be changed in future iterations.

**Comment by Bailey-24** [comment]
Thank you. The main application is in future iterations to change robot trajectory.
But the current system can't change online, right?

**Comment by arthurfenderbucker** [comment]
Yes it can, the system was running in about 2 seconds in the tested setup. However, online modifications of the trajectory would only make sense if the user was able to identify beforehand what to change in the original trajectory. That could be done either by looking at the trajectory plan or by knowing the expected behavior from previous runs.
